# This file is part of prompt_publication_service.
#
# Developed for the LSST Data Management System.
# This product includes software developed by the LSST Project
# (https://www.lsst.org).
# See the COPYRIGHT file at the top-level directory of this distribution
# for details of code ownership.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


import click

from lsst.daf.butler import Butler, CollectionType
from lsst.daf.butler._rubin.transfer_datasets_in_place import transfer_datasets_in_place
from lsst.pipe.base import Instrument

from ..tasks.publish_to_google import OUTPUT_TAGGED_COLLECTION


@click.command()
@click.argument("source_repo")
@click.argument("target_repo")
def initialize_google_repo(source_repo: str, target_repo: str) -> None:
    """Initialize the basic contents of an end-user repository (LSSTCam
    instrument records, skymap, and collection chains.)
    """
    with (
        Butler.from_config(source_repo) as source_butler,
        Butler.from_config(target_repo, writeable=True) as target_butler,
    ):
        print("Registering LSSTCam instrument")
        instrument = Instrument.from_string("lsst.obs.lsst.LsstCam")
        instrument.register(target_butler.registry, update=True)

        print("Looking up skymap from source repo")
        skymap_data_id = {"skymap": "lsst_cells_v2"}
        skymap_ref = source_butler.find_dataset("skyMap", skymap_data_id, collections="skymaps")
        assert skymap_ref is not None, f"Couldn't find skymap '{skymap_data_id}' in source repository"
        print("Transferring skymap to target repo")
        target_butler.transfer_dimension_records_from(source_butler, [skymap_ref])
        transfer_datasets_in_place(source_butler, target_butler, [skymap_ref])
        for dimension in ("tract", "patch"):
            print(f"Looking up {dimension} records")
            records = source_butler.query_dimension_records(dimension, data_id=skymap_data_id, limit=None)
            print(f"Inserting {dimension} records")
            target_butler.registry.insertDimensionData(dimension, *records, replace=True)

        print("Registering collections")
        target_butler.collections.register(
            "Prompt/All",
            CollectionType.CHAINED,
            "All Prompt Data Products that have ever been published,"
            " including those that can no longer be downloaded.",
        )
        target_butler.collections.register(
            "Prompt/Available",
            CollectionType.CHAINED,
            "All Prompt Data Products that are currently available for download.",
        )
        target_butler.collections.register(
            OUTPUT_TAGGED_COLLECTION,
            CollectionType.TAGGED,
            "Prompt Data Products generated by Prompt Processing that are currently available for download.",
        )
        target_butler.collections.register(
            "Prompt/Expired",
            CollectionType.CHAINED,
            "All Prompt Data Products that were previously published but no longer available for download.",
        )
        target_butler.collections.register(
            "Prompt/Expired/Outputs",
            CollectionType.TAGGED,
            "Prompt Data Products generated by Prompt Processing that were previously published"
            " but no longer available for download.",
        )
        target_butler.collections.redefine_chain("Prompt/All", ["Prompt/Available", "Prompt/Expired"])
        target_butler.collections.redefine_chain("Prompt/Available", ["skymaps", OUTPUT_TAGGED_COLLECTION])
        target_butler.collections.redefine_chain("Prompt/Expired", ["Prompt/Expired/Outputs"])

        print("Done")


if __name__ == "__main__":
    initialize_google_repo()
