# This file is part of prompt_publication_service.
#
# Developed for the LSST Data Management System.
# This product includes software developed by the LSST Project
# (https://www.lsst.org).
# See the COPYRIGHT file at the top-level directory of this distribution
# for details of code ownership.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

import asyncio

import click
from lsst.daf.butler import Butler
from lsst.resources import ResourcePath

from ..database import Database
from ..register import register_dataset_batch_file
from ..schema import DatasetOrigin


@click.command()
@click.argument("butler_repo")
@click.argument("database_uri")
@click.argument("batch_files", nargs=-1)
def register_embargo_datasets_from_collections(
    butler_repo: str, database_uri: str, batch_files: tuple[str, ...]
) -> None:
    """Script that adds datasets to the state database from a JSON batch file
    generated by the Prompt Processing Butler Writer.
    """
    with Butler.from_config(butler_repo) as butler:
        for batch_file in batch_files:
            path = ResourcePath(batch_file, forceDirectory=False)
            asyncio.run(_register_datasets(butler, database_uri, path))


async def _register_datasets(butler: Butler, database_uri: str, batch_file: ResourcePath) -> None:
    async with Database(database_uri) as db:
        await register_dataset_batch_file(db, DatasetOrigin.PROMPT_PROCESSING, butler, batch_file)


if __name__ == "__main__":
    register_embargo_datasets_from_collections()
