"""Initial schema

Revision ID: c09aa0e87f8b
Revises:
Create Date: 2025-12-16 14:39:11.879941

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import lsst.prompt_publication_service.schema
import lsst.prompt_publication_service.database


# revision identifiers, used by Alembic.
revision: str = "c09aa0e87f8b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "unknown_dataset",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("origin", lsst.prompt_publication_service.schema._EnumColumn(), nullable=False),
        sa.Column("error", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "visit",
        sa.Column("visit", sa.BigInteger(), nullable=False),
        sa.Column("instrument", sa.String(), nullable=False),
        sa.Column("time", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("visit", "instrument"),
    )
    op.create_table(
        "dataset",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("origin", lsst.prompt_publication_service.schema._EnumColumn(), nullable=False),
        sa.Column("dataset_type", sa.String(), nullable=False),
        sa.Column("instrument", sa.String(), nullable=True),
        sa.Column("visit", sa.BigInteger(), nullable=True),
        sa.Column("embargo_status", lsst.prompt_publication_service.schema._EnumColumn(), nullable=False),
        sa.Column("prompt_prep_status", lsst.prompt_publication_service.schema._EnumColumn(), nullable=False),
        sa.Column("repo_main_status", lsst.prompt_publication_service.schema._EnumColumn(), nullable=False),
        sa.Column("google_int_status", lsst.prompt_publication_service.schema._EnumColumn(), nullable=False),
        sa.Column("google_prod_status", lsst.prompt_publication_service.schema._EnumColumn(), nullable=False),
        sa.Column("unembargo_time", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["visit", "instrument"],
            ["visit.visit", "visit.instrument"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "embargo_status_lookup",
        "dataset",
        ["embargo_status", "prompt_prep_status", "dataset_type"],
        unique=False,
    )
    op.create_index(
        "google_int_status_lookup",
        "dataset",
        ["google_int_status", "prompt_prep_status", "dataset_type"],
        unique=False,
    )
    op.create_index(
        "google_prod_status_lookup",
        "dataset",
        ["google_prod_status", "prompt_prep_status", "dataset_type"],
        unique=False,
    )
    op.create_index(
        "repo_main_status_lookup",
        "dataset",
        ["repo_main_status", "prompt_prep_status", "dataset_type"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("repo_main_status_lookup", table_name="dataset")
    op.drop_index("google_prod_status_lookup", table_name="dataset")
    op.drop_index("google_int_status_lookup", table_name="dataset")
    op.drop_index("embargo_status_lookup", table_name="dataset")
    op.drop_table("dataset")
    op.drop_table("visit")
    op.drop_table("unknown_dataset")
    # ### end Alembic commands ###
