name: Run mypy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: 0.10.x
      - run: uv run --frozen mypy
